
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '2F36BC4CC6095698890C6906E9A67749'
    
_lr_action_items = {'LPAR':([1,],[3,]),'ELEMENTS':([3,],[5,]),'NAME':([3,],[7,]),'RPAR':([3,5,6,7,],[8,9,10,11,]),'NUM':([3,],[6,]),'ACTION':([0,],[1,]),'$end':([1,2,4,8,9,10,11,],[-2,0,-1,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'parameters':([1,],[4,]),'statement':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ACTION parameters','statement',2,'p_statement','quickvu.py',85),
  ('statement -> ACTION','statement',1,'p_statement','quickvu.py',86),
  ('parameters -> LPAR RPAR','parameters',2,'p_parameter','quickvu.py',115),
  ('parameters -> LPAR ELEMENTS RPAR','parameters',3,'p_parameter','quickvu.py',116),
  ('parameters -> LPAR NUM RPAR','parameters',3,'p_parameter','quickvu.py',117),
  ('parameters -> LPAR NAME RPAR','parameters',3,'p_parameter','quickvu.py',118),
]
