
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '4DEC5E5738CBB2C01F646387111FCE05'
    
_lr_action_items = {'ELEMENTS':([9,],[13,]),'NAME':([9,],[14,]),'LANK':([0,1,3,4,8,11,16,17,],[-1,2,6,-2,-4,-3,-6,-5,]),'RANK':([5,7,10,12,13,14,15,],[8,11,16,-8,-7,-9,17,]),'NUM':([9,],[12,]),'WS':([0,1,4,5,8,10,11,16,17,],[-1,3,-2,9,-4,9,-3,-6,-5,]),'ACTION':([2,6,],[5,10,]),'$end':([0,1,4,8,11,16,17,],[-1,0,-2,-4,-3,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'parameters':([5,10,],[7,15,]),'statement':([1,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> <empty>','statements',0,'p_statements','quickvu.py',59),
  ('statements -> statements statement','statements',2,'p_statements','quickvu.py',60),
  ('statement -> LANK ACTION parameters RANK','statement',4,'p_statement','quickvu.py',64),
  ('statement -> LANK ACTION RANK','statement',3,'p_statement','quickvu.py',65),
  ('statement -> WS LANK ACTION parameters RANK','statement',5,'p_statement','quickvu.py',66),
  ('statement -> WS LANK ACTION RANK','statement',4,'p_statement','quickvu.py',67),
  ('parameters -> WS ELEMENTS','parameters',2,'p_parameters','quickvu.py',113),
  ('parameters -> WS NUM','parameters',2,'p_parameters','quickvu.py',114),
  ('parameters -> WS NAME','parameters',2,'p_parameters','quickvu.py',115),
]
